[package]
name = "stave"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-to-tui = "7.0.0"
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"
